### ISSUE TITLE
Issue with FastQC

### ISSUE THREAD

**Issue by jsangalang** [nf-core/rnavar#76]
Hello,

There seems to be an issue when I run the pipeline, in particular the FASTQC step. It says an .html was expected but not found. I am using singularity on the SLURM executor for the cluster.

```
executor >  slurm (31)
[14/7169cf] process > NFCORE_RNAVAR:RNAVAR:PREPAR... [100%] 1 of 1, cached: 1 ✔
[73/d2ddbd] process > NFCORE_RNAVAR:RNAVAR:PREPAR... [100%] 1 of 1, cached: 1 ✔
[e0/b4b70a] process > NFCORE_RNAVAR:RNAVAR:PREPAR... [100%] 1 of 1, cached: 1 ✔
[69/2373fc] process > NFCORE_RNAVAR:RNAVAR:INPUT_... [100%] 1 of 1, cached: 1 ✔
[94/d944ca] process > NFCORE_RNAVAR:RNAVAR:CAT_FA... [100%] 5 of 5, cached: 5 ✔
[64/c92479] process > NFCORE_RNAVAR:RNAVAR:FASTQC... [ 22%] 26 of 116, cached...
[c4/c6953d] process > NFCORE_RNAVAR:RNAVAR:GATK4_... [100%] 1 of 1, cached: 1 ✔
[eb/b9d249] process > NFCORE_RNAVAR:RNAVAR:GATK4_... [100%] 1 of 1 ✔
[bb/4dd180] process > NFCORE_RNAVAR:RNAVAR:ALIGN_... [ 12%] 14 of 116, cached...
[6f/91715c] process > NFCORE_RNAVAR:RNAVAR:ALIGN_... [ 57%] 8 of 14
[-        ] process > NFCORE_RNAVAR:RNAVAR:ALIGN_... [  0%] 0 of 8
[-        ] process > NFCORE_RNAVAR:RNAVAR:ALIGN_... -
[-        ] process > NFCORE_RNAVAR:RNAVAR:ALIGN_... -
[-        ] process > NFCORE_RNAVAR:RNAVAR:ALIGN_... -
[-        ] process > NFCORE_RNAVAR:RNAVAR:MARKDU... [  0%] 0 of 8
[-        ] process > NFCORE_RNAVAR:RNAVAR:MARKDU... -
[-        ] process > NFCORE_RNAVAR:RNAVAR:MARKDU... -
[-        ] process > NFCORE_RNAVAR:RNAVAR:MARKDU... -
[-        ] process > NFCORE_RNAVAR:RNAVAR:MARKDU... -
[-        ] process > NFCORE_RNAVAR:RNAVAR:SPLITN... -
[-        ] process > NFCORE_RNAVAR:RNAVAR:SPLITN... -
[-        ] process > NFCORE_RNAVAR:RNAVAR:SPLITN... -
[-        ] process > NFCORE_RNAVAR:RNAVAR:GATK4_... -
[-        ] process > NFCORE_RNAVAR:RNAVAR:RECALI... -
[-        ] process > NFCORE_RNAVAR:RNAVAR:RECALI... -
[-        ] process > NFCORE_RNAVAR:RNAVAR:RECALI... -
[-        ] process > NFCORE_RNAVAR:RNAVAR:GATK4_... -
[-        ] process > NFCORE_RNAVAR:RNAVAR:GATK4_... -
[-        ] process > NFCORE_RNAVAR:RNAVAR:TABIX     -
[-        ] process > NFCORE_RNAVAR:RNAVAR:GATK4_... -
[-        ] process > NFCORE_RNAVAR:RNAVAR:ANNOTA... -
[-        ] process > NFCORE_RNAVAR:RNAVAR:ANNOTA... -
[-        ] process > NFCORE_RNAVAR:RNAVAR:ANNOTA... -
[-        ] process > NFCORE_RNAVAR:RNAVAR:ANNOTA... -
[-        ] process > NFCORE_RNAVAR:RNAVAR:CUSTOM... -
[-        ] process > NFCORE_RNAVAR:RNAVAR:MULTIQC   [  0%] 0 of 1
Error executing process > 'NFCORE_RNAVAR:RNAVAR:FASTQC (B02051)'

Caused by:
  Missing output file(s) `*.html` expected by process `NFCORE_RNAVAR:RNAVAR:FASTQC (B02051)`

Command executed:

  [ ! -f  B02051_1.fastq.gz ] && ln -s A006AUPB1.R1.fastq.gz B02051_1.fastq.gz
  [ ! -f  B02051_2.fastq.gz ] && ln -s A006AUPB1.R2.fastq.gz B02051_2.fastq.gz
  fastqc --quiet --threads 6 B02051_1.fastq.gz B02051_2.fastq.gz
  
  cat <<-END_VERSIONS > versions.yml
  "NFCORE_RNAVAR:RNAVAR:FASTQC":
      fastqc: $( fastqc --version | sed -e "s/FastQC v//g" )
  END_VERSIONS

Command exit status:
  0

Command output:
  (empty)

Command error:
  WARNING: Skipping mount /mnt/beegfs/software/singularity/3.6.3/var/singularity/mnt/session/etc/resolv.conf [files]: /etc/resolv.conf doesn't exist in container
  Failed to process file B02051_2.fastq.gz
  java.lang.IllegalArgumentException: image == null!
  	at java.desktop/javax.imageio.ImageTypeSpecifier.createFromRenderedImage(ImageTypeSpecifier.java:925)
  	at java.desktop/javax.imageio.ImageIO.getWriter(ImageIO.java:1608)
  	at java.desktop/javax.imageio.ImageIO.write(ImageIO.java:1594)
  	at uk.ac.babraham.FastQC.Utilities.ImageToBase64.imageToBase64(ImageToBase64.java:38)
  	at uk.ac.babraham.FastQC.Report.HTMLReportArchive.base64ForIcon(HTMLReportArchive.java:380)
  	at uk.ac.babraham.FastQC.Report.HTMLReportArchive.startDocument(HTMLReportArchive.java:303)
  	at uk.ac.babraham.FastQC.Report.HTMLReportArchive.<init>(HTMLReportArchive.java:84)
  	at uk.ac.babraham.FastQC.Analysis.OfflineRunner.analysisComplete(OfflineRunner.java:185)
  	at uk.ac.babraham.FastQC.Analysis.AnalysisRunner.run(AnalysisRunner.java:123)
  	at java.base/java.lang.Thread.run(Thread.java:834)
  Failed to process file B02051_1.fastq.gz
  java.lang.IllegalArgumentException: image == null!
  	at java.desktop/javax.imageio.ImageTypeSpecifier.createFromRenderedImage(ImageTypeSpecifier.java:925)
  	at java.desktop/javax.imageio.ImageIO.getWriter(ImageIO.java:1608)
  	at java.desktop/javax.imageio.ImageIO.write(ImageIO.java:1594)
  	at uk.ac.babraham.FastQC.Utilities.ImageToBase64.imageToBase64(ImageToBase64.java:38)
  	at uk.ac.babraham.FastQC.Report.HTMLReportArchive.base64ForIcon(HTMLReportArchive.java:380)
  	at uk.ac.babraham.FastQC.Report.HTMLReportArchive.startDocument(HTMLReportArchive.java:303)
  	at uk.ac.babraham.FastQC.Report.HTMLReportArchive.<init>(HTMLReportArchive.java:84)
  	at uk.ac.babraham.FastQC.Analysis.OfflineRunner.analysisComplete(OfflineRunner.java:185)
  	at uk.ac.babraham.FastQC.Analysis.AnalysisRunner.run(AnalysisRunner.java:123)
  	at java.base/java.lang.Thread.run(Thread.java:834)

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line
```

And my bash script to run:
```
#!/bin/bash

module load java/12.0.2
module load singularity
module load nextflow

nextflow run /mnt/beegfs/scratch/nf-core_rnavar/rnavar-1.0.0/main.nf \
--igenomes_base '/mnt/beegfs/iGenome' \
--input '/mnt/beegfs/scratch/nf-core_rnavar/sample_plan.csv' \
--outdir '/mnt/beegfs/scratch/nf-core_rnvar/pipeline_results' \
--annotate_tools merge \
--save_reference \
-profile singularity \
--known_indels '/mnt/beegfs/database/GATK_resources_bundle_hg38_v0/Homo_sapiens_assembly38.known_indels.vcf.gz' \
--known_indels_tbi '/mnt/beegfs/database/GATK_resources_bundle_hg38_v0/Homo_sapiens_assembly38.known_indels.vcf.gz.tbi' \
--dbsnp '/mnt/beegfs/database/GATK_resources_bundle_hg38_v0/Homo_sapiens_assembly38.dbsnp138.vcf' \
--vep_cache_version \'107\' \
--vep_species 'homo_sapiens' \
--vep_genome 'GRCh38' \
--genome GRCh38 \
--snpeff_db '/mnt/beegfs/database/snpeff/data/GRCh38.85' \
--star_index '/mnt/beegfs/database/Human/hg38/indexes/STAR_2.7.6a'
```

**Comment by nvnieuwk** [comment]
Hi, I'm not sure if you are still having this issue. This however seems to be an issue with your FASTQ file. I'm not able to reproduce this error without an example data set. I'll be closing this issue now as it's pretty old already, but feel free to reopen it if you have more information on this problem
